version: '3.3'
services:

    request-handler:
        build:
            context: ../../
            args:
              DIR: request-handler
            dockerfile: ./request-handler/deploy_test/service.Dockerfile
        container_name: request-handler
        depends_on:
            - activemq
            - db
        environment:
            NETWORK: $NETWORK
            DATABASE_URL: $DATABASE_URL
            MQ_CONNECTION_URL: $MQ_CONNECTION_URL

        env_file:
            - ../.env${ENVIRONMENT}

        image: request-handler
        networks:
            - subsystems
        tty: true
        restart: always

    db:
        build:
            context: ../../
            dockerfile: deploy/db.Dockerfile
        container_name: db
        networks:
            - subsystems
        ports:
            - 5432:5432
        environment:
            DB_PORT: 5432
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

    activemq:
        image: rmohr/activemq:5.14.5
        container_name: activemq
        networks:
            - subsystems
        ports:
            - 61613:61613
            - 8161:8161

networks:
    subsystems:
        driver: bridge
