version: '3.3'
services:

    request-reader:
        build:
            context: .
            args:
              DIR: ../request-reader
            dockerfile: service.Dockerfile
        container_name: request-reader
        depends_on:
            - db
            - activemq
        environment:
            PORT: 3003
            DATABASE_URL: postgres://postgres:secret@db/stoxbcrm
            NETWORK: MAIN
            MQ_CONNECTION_URL: stomp://activemq:61613
        image: request-reader
        networks:
            - subsystems
        tty: true
        restart: always

    db:
        image: stox-regitry/stoxdb:10.3
        container_name: db
        networks:
            - subsystems
        ports:
            - 5434:5432
        environment:
            POSTGRES_PASSWORD: secret
            POSTGRES_USER: postgres
            POSTGRES_DB: stoxbcrm

    activemq:
        image: rmohr/activemq:5.14.5
        container_name: activemq
        networks:
            - subsystems
        ports:
            - 61613:61613
            - 8161:8161

networks:
    subsystems:
        driver: bridge
